import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faCloudArrowUp,
    faMicrophone,
    faBolt,
    faArrowRight,
    faRotateRight,
    faFileAudio,
    faGauge,
    faWandMagicSparkles,
    faStar,
    faCommentDots,
    faClipboardList,
    faCircleCheck,
    faTriangleExclamation,
    faChartSimple,
    faChartLine,
    faUserCircle,
    faInfoCircle,
    faCheck,
    faPause,
    faPlay,
    faCircle,
    faStop,
    faRedo,
    faPlus,
    faFolder,
    faFolderPlus,
    faTimes,
    faArrowLeft,
    faList,
    faMicrophoneSlash,
    faCircleExclamation,
    faLock,
    faChalkboardUser,
    faPaperPlane,
    faRobot,
    faFileLines
} from '@fortawesome/free-solid-svg-icons';

import {
    faClock as farClock
} from '@fortawesome/free-regular-svg-icons';

library.add(
    faMicrophone,
    faCloudArrowUp,
    faBolt,
    faArrowRight,
    farClock,
    faRotateRight,
    faFileAudio,
    faGauge,
    faWandMagicSparkles,
    faStar,
    faCommentDots,
    faClipboardList,
    faCircleCheck,
    faTriangleExclamation,
    faChartSimple,
    faChartLine,
    faUserCircle,
    faInfoCircle,
    faCheck,
    faPause,
    faPlay,
    faCircle,
    faStop,
    faRedo,
    faPlus,
    faFolder,
    faFolderPlus,
    faTimes,
    faArrowLeft,
    faList,
    faMicrophoneSlash,
    faCircleExclamation,
    faLock,
    faChalkboardUser,
    faPaperPlane,
    faRobot,
    faFileLines
);
